#!/usr/bin/env python3
"""Validate skills/ and regenerate CATALOG.md.

Checks every skills/<category>/<name>/SKILL.md for:
  - frontmatter with name and description
  - name matching its folder, lowercase-hyphenated, globally unique
  - name prefix matching its category
  - no SKILL.md shadowing at the category level

Usage: python3 scripts/check_skills.py [--check]   (--check: fail if CATALOG.md is stale)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
CATALOG = ROOT / "CATALOG.md"

CATEGORIES = {
    "core": ("fm", "Core conventions", "Shared by every model: layout, formatting, timing, checks."),
    "real-estate": ("re", "Real estate", "Acquisitions, development, waterfalls, debt."),
    "project-finance": ("pf", "Project finance", "CFADS, debt sizing and sculpting, reserves, cover ratios."),
    "investment-banking": ("ib", "Investment banking", "LBO, merger, comps, DCF."),
    "corporate-finance": ("cf", "Corporate finance", "Three-statement models, budgeting, forecasting."),
}
NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
MAX_DESCRIPTION = 1024


def frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fields = {}
    for line in m.group(1).splitlines():
        key, sep, value = line.partition(":")
        if sep and not line.startswith((" ", "\t")):
            fields[key.strip()] = value.strip().strip("\"'")
    return fields


def main():
    errors, rows, seen = [], {c: [] for c in CATEGORIES}, {}

    for category_dir in sorted(p for p in SKILLS.iterdir() if p.is_dir()):
        category = category_dir.name
        if category not in CATEGORIES:
            errors.append(f"skills/{category}: unknown category (add it to CATEGORIES)")
            continue
        if (category_dir / "SKILL.md").exists():
            errors.append(f"skills/{category}/SKILL.md shadows every skill in the category")
        prefix = CATEGORIES[category][0]

        for skill_md in sorted(category_dir.glob("*/SKILL.md")):
            rel = skill_md.relative_to(ROOT)
            folder = skill_md.parent.name
            fm = frontmatter(skill_md.read_text())
            if fm is None:
                errors.append(f"{rel}: missing frontmatter")
                continue
            name, desc = fm.get("name", ""), fm.get("description", "")
            if name != folder:
                errors.append(f"{rel}: name '{name}' does not match folder '{folder}'")
            if not NAME_RE.match(name):
                errors.append(f"{rel}: name must be lowercase-hyphenated")
            if not name.startswith(prefix + "-"):
                errors.append(f"{rel}: name must start with '{prefix}-' in {category}/")
            if name in seen:
                errors.append(f"{rel}: name duplicates {seen[name]}")
            seen[name] = rel
            if not desc:
                errors.append(f"{rel}: missing description")
            elif len(desc) > MAX_DESCRIPTION:
                errors.append(f"{rel}: description over {MAX_DESCRIPTION} characters")
            rows[category].append((name, desc, skill_md.parent.relative_to(ROOT)))

    lines = [
        "# Catalog",
        "",
        "<!-- Generated by scripts/check_skills.py; do not edit by hand. -->",
        "",
        "Install one skill: `npx skills add <owner>/moolaski --skill <name>`",
        "",
    ]
    for category, (prefix, title, blurb) in CATEGORIES.items():
        lines += [f"## {title} (`{prefix}-*`)", "", blurb, ""]
        if rows[category]:
            lines += ["| Skill | Use when |", "|---|---|"]
            lines += [f"| [{n}]({p}/SKILL.md) | {d} |" for n, d, p in rows[category]]
        else:
            lines.append("_No skills yet._")
        lines.append("")
    catalog = "\n".join(lines)

    if "--check" in sys.argv[1:]:
        if not CATALOG.exists() or CATALOG.read_text() != catalog:
            errors.append("CATALOG.md is stale; run scripts/check_skills.py")
    else:
        CATALOG.write_text(catalog)

    for e in errors:
        print(f"error: {e}", file=sys.stderr)
    print(f"{len(seen)} skills, {len(errors)} errors")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
